AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds/*'
    - 'db/seeds.rb'
    - 'bin/*'

Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 16
Metrics/BlockNesting:
  Max: 4